# Generated by Django 4.2.16 on 2025-03-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PxData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('px_id', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.CharField(blank=True, max_length=50, null=True)),
                ('sex', models.CharField(blank=True, max_length=50, null=True)),
                ('sechool', models.CharField(blank=True, max_length=50, null=True)),
                ('sessions', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pretest_rec', models.FileField(blank=True, null=True, upload_to='recordings/')),
                ('pretest_time', models.CharField(blank=True, max_length=50, null=True)),
                ('pretest_score', models.CharField(blank=True, max_length=50, null=True)),
                ('test_a_rec', models.FileField(blank=True, null=True, upload_to='recordings/')),
                ('test_a_time', models.CharField(blank=True, max_length=50, null=True)),
                ('test_a_score', models.CharField(blank=True, max_length=50, null=True)),
                ('test_b_rec', models.FileField(blank=True, null=True, upload_to='recordings/')),
                ('test_b_time', models.CharField(blank=True, max_length=50, null=True)),
                ('test_b_score', models.CharField(blank=True, max_length=50, null=True)),
                ('test_c_rec', models.FileField(blank=True, null=True, upload_to='recordings/')),
                ('test_c_time', models.CharField(blank=True, max_length=50, null=True)),
                ('test_c_score', models.CharField(blank=True, max_length=50, null=True)),
                ('session_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
