# Generated by Django 4.2.16 on 2025-03-22 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DEMApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pxdata',
            old_name='sechool',
            new_name='school',
        ),
    ]
