# Generated by Django 4.2.16 on 2025-03-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DEMApp', '0002_rename_sechool_pxdata_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdata',
            name='pretest_raw',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
