# Generated by Django 4.2.16 on 2025-03-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DEMApp', '0003_testdata_pretest_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdata',
            name='test_a_raw',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='testdata',
            name='test_b_raw',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='testdata',
            name='test_c_raw',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
