# Generated by Django 4.2.16 on 2025-03-28 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DEMApp', '0004_testdata_test_a_raw_testdata_test_b_raw_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testdata',
            old_name='test_a_score',
            new_name='test_a_omissions',
        ),
        migrations.RenameField(
            model_name='testdata',
            old_name='test_b_score',
            new_name='test_b_omissions',
        ),
        migrations.RenameField(
            model_name='testdata',
            old_name='test_c_score',
            new_name='test_c_omissions',
        ),
    ]
