# Generated by Django 4.2.16 on 2025-03-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DEMApp', '0005_rename_test_a_score_testdata_test_a_omissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdata',
            name='test_a_additions',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testdata',
            name='test_b_additions',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
