# Generated by Django 4.2.16 on 2025-03-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DEMApp', '0006_testdata_test_a_additions_testdata_test_b_additions'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdata',
            name='test_c_additions',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
